---
title: "Participación Ciudadana Juvenil"
output: pdf_document
---

```{r echo=FALSE}
knitr::opts_chunk$set(out.width="80%", fig.pos = "!ht", out.extra = "") 
```

# Resumen del proyecto {-}

A pesar de la importancia de la persistente desigualdad política y los bajos niveles de involucramiento ciudadano juvenil no se sabe demasiado acerca de cómo los procesos de socialización reproducen y/o socializan estas desigualdades de una generación a otra. A este respecto, aunque es innegable la importancia de varios agentes de socialización política, como la escuela, existe un amplio consenso que plantea que el principal agente socializador de esta dimensión de la vida es la familia. Sin embargo, existen aún varios elementos necesarios de profundizar para comprender mejor el rol de la familia para el desarrollo de las formas de involucramiento ciudadano de los jóvenes. Primero, no es claro aún si esta transmisión se produce de igual manera con los diferentes tipos de participación. Segundo, si bien la transmisión de ventajas comparativas ha sido abordada ampliamente desde la sociología, expresado por ejemplo en el estudio de la transmisión del logro educacional o el estudio de la reproducción social, existe limitada evidencia acerca de cuáles son los mecanismos a través de los cuales opera esta transmisión en el ámbito político. Finalmente, no es claro si los efectos que tienen las condiciones socioeconómicas y/o las prácticas de socialización en edades tempranas se sostienen a lo largo del tiempo. 

Este proyecto trata acerca de la siguiente pregunta de investigación general: ¿Cuáles son los factores y mecanismos que explican la transmisión intergeneracional de la desigualdad política? Para responder esta pregunta global se analizará el rol que cumplen tanto las características socioeconómicas como las prácticas de socialización política de la familia para el desarrollo de diferentes tipos de participación ciudadana que manifiestan los jóvenes, tales como participación formal, participación activista y/o participación comunitaria. Adicionalmente, se evaluará la estabilidad o cambio de estas fuentes de socialización en diferentes momentos del desarrollo juvenil. 

Esta propuesta de investigación busca integrar dos perspectivas sociológicas a través de un modelo, para comprender la participación ciudadana juvenil en sus distintas formas. Por un lado, una perspectiva normativista vinculada a la formación para la ciudadanía desde los agentes de socialización política. Por otro lado, una perspectiva fundada en el rol de los factores socioeconómicos y la transmisión del estatus. Estas dos literaturas se han desarrollado en general de manera separada, observándose poco diálogo entre ellas. En síntesis, se estudiará la asociación entre las condiciones socioeconómicas de origen familiar con los diferentes tipos de participación de la siguiente generación, el rol mediador que tienen las prácticas de socialización política de la familia y el estatus adquirido por los jóvenes a través de la socialización familiar; y también, la estabilidad que tienen dichos procesos.