---
title: "Participación Ciudadana Juvenil"
subtitle: "Reporte de resultados Primera Ola 2021"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
fontsize: 14pt
# mainfont: Palatino
# monofont: "Source Code Pro"
# monofontoptions: "Scale=0.8"
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
---

# Introducción {-}

Este reporte resume los principales resultados de la primera ola del estudio Panel de Participación Ciudadana Juvenil. Este estudio es parte del proyecto Fondecyt de Iniciación N°11190508 "Participación ciudadana juvenil: entre la Reproducción social y la socialización política.".

Estructura del reporte:

**Resumen del proyecto**

**Módulo 1: Análisis descriptivo de las variables principales**

- 1.1 Participación ciudadana
- 1.2 Prácticas de socialización política

**Módulo 2: Hipótesis de recursos**

- 2.1 Recursos socioeconómicos familiares y participación ciudadana 
- 2.2 Recursos socioeconómicos propios y participación ciudadana 

**Módulo 3: Hipótesis de reproducción de estatus**

- 3.1 Reproducción de estatus y participación ciudadana
- 3.2 Efectos según tipo de participación

**Módulo 4: Hipótesis de socialización política familiar**

- 4.1 Socialización política familiar y participación ciudadana
- 4.2 Efectos según tipo de participación

**Módulo 5: Hipótesis de estratificación de la socialización política**

- 5.1 Recursos socioeconómicos y prácticas de socialización política

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```